# GYM MANAGEMENT SYSTEM BY PEACE OLORUNTOBA C.E.O. PEASCAINC
# You can contact me on gmail @ profprincepeace@gmail.com or peascainc@gmail.com
# You can also call me or whatsapp me on +2348166846226

# Generated by Django 3.2 on 2021-08-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
